client_name: Larkmead
farm_name: Larkmead Vineyards
block_name: A3a-North
session_name: a3a-north
test: True
exclude_scans:
include_scans: [2017-08-30_07-13]
role: rvm
detection_params:
        caffemodel_s3_url_cluster: s3://deeplearning_data/models/best/wine-black-56000-9-3-2017.caffemodel
        caffemodel_s3_url_trunk: s3://deeplearning_data/models/best/trunk_june_10_400000.caffemodel