client_name: Larkmead
farm_name: Larkmead Vineyards
block_name: C10-West
session_name: c10west
test: 0
exclude_scans:
include_scans: [2017-08-31_15-06, 2017-09-01_07-39]
role: rvm
detection_params:
        caffemodel_s3_url_cluster: s3://deeplearning_data/models/best/wine-black-56000-9-3-2017.caffemodel
        caffemodel_s3_url_trunk: s3://deeplearning_data/models/best/trunk_june_10_400000.caffemodel