client_name: Harlan Estate
farm_name: Harlan Estate
block_name: 5G
session_name: nov9-5g
test: False
exclude_scans:
include_scans: [2017-09-08_10-48]
role: rvm
detection_params:
        caffemodel_s3_url_cluster: s3://deeplearning_data/models/best/wine-nov-06.caffemodel
        caffemodel_s3_url_trunk: s3://deeplearning_data/models/best/trunk_june_10_400000.caffemodel