client_name: Harlan Estate
farm_name: Promontory
block_name: 6B
session_name: 6b
test: False
exclude_scans:
include_scans: [2017-09-09_14-03]
role: rvm
detection_params:
        caffemodel_s3_url_cluster: s3://deeplearning_data/models/best/wine-black-96000-9-7-2017.caffemodel
        caffemodel_s3_url_trunk: s3://deeplearning_data/models/best/trunk_june_10_400000.caffemodel
